### ISSUE TITLE
linux下运行程序打开摄像头后异常退出

### ISSUE THREAD

**Issue by jia0511** [liuguiyangnwpu/HandGesture#1]
Dear master,

感谢你的贡献！
我在ubuntu系统下遇到了运行程序后打开摄像头crash的问题,所有想请教还有什么是需要注意的，或者你有在linux下通过运行的案例吗，我环境是ubuntu16.04+opencv2.4

**Comment by jia0511** [comment]
补充说下，打开摄像头，readframe()函数中，进行图像转换iplimage2qimage后，设置显示尺寸image.scaled时出现段错误，使用非法内存，难到这段代码转换还有问题？？？

**Comment by guiyang882** [comment]
@jia0511 你好！我在我的mac中没有问题，我现在使用的使用Opencv3.2.0 + Qt5.6

这么晚回复您！实在不好意思！

**Comment by guiyang882** [comment]
@jia0511 我最近会在我的电脑中在调试一下看看具体哪里有问题！

**Comment by liuguiyangnwpu** [comment]
@jia0511 我最近会在我的电脑中在调试一下看看具体哪里有问题！

**Comment by guiyang882** [comment]
您好！关于不能运行的问题，我应该已经修复过了！您在试验一下，我在我自己的电脑端是没有问题的！

**Comment by jia0511** [comment]
maybe在你设备上ok,但是能告诉我配置上的一些差异吗

**Comment by guiyang882** [comment]
你得关注下conf文件，在main函数中关于config的路径配置问题，如果你想自己训练数据的话，请到工程中的data/目录中去下载指定的百度云中的数据集，可以免费下载！

PS：
补充一句，能否把你的调试信息截图贴一下，这样我能更好的帮助你解决问题？

**Comment by jia0511** [comment]
谢谢你的反馈 这几天工作比较忙没有及时回复，等周末再发给你。

**Comment by jia0511** [comment]
1.在你的版本中我找不到.pro的工程
2.程序是异常退出，没有打印信息
3.我使用opencv3.2提示找不到contrib.hpp的头文件，所以我回到2.4
4.相应配置我已经更改
5.我又下载此博客提供的项目http://blog.csdn.net/berguiliu/article/details/9307495 还是出错

**Comment by jia0511** [comment]
关于第五点 我已解决问题 但是你去除了一些功能 看不到结果

**Comment by jia0511** [comment]
请你开源完整的代码，可以直接应用的

**Comment by guiyang882** [comment]
hi @jia0511 ,
你好！首先感谢您的关注。
1.我现在使用的CMake的模式进行开发，不用QtCreator本身的IDE，因此没有pro文件，但是有cmakefile.txt文件，如果你熟悉配置cmake的话，这个是很简单可以用的。
2.如果没有打印信息可以在你的环境中自行debug
3.对于找不到contrib.hpp，估计是你对opencv不够了解，不知道高版本的opencv3.x如果正确安装，以及如何扩展使用contrib，希望你去stackoverflow中去查找下入和在ubuntu中安装opencv3.2 with contrib
4.对于CSDN中的历史版本的文件，我已经不在维护了，因此老本版有问题，请更换成新版本。
5. 我的确开源了我的所有代码，未加保留，并且我的确在我本地测试通过。
我近期在ubuntu上进行测试，看看啥问题。（ 希望您按照教程将contrib安装下）

thx

**Comment by jia0511** [comment]
Good day!@liuguiyang
contrib已经安装，但是任然存在该问题，代码中在qt UI识别按钮 按下后代码没有识别部分的调用，cmake 使用存在编译问题，至于标题的异常退出那是没有检测/dev/video0是否存在而直接调用导致，如果方便想和你电话沟通。

**Comment by jia0511** [comment]
博主，如果不方便请问两个问题：
1、在识别图片角度与非角度时为什么要分为5层？
2、在计算运动轨迹时，传递的宽与高指的是手掌矩形的宽高？
